name: Run Tests Allure Report and GitHub Pages.

on:
  push:
  pull_request:

jobs:
  test:
    name: Rodar Testes JUnit
    runs-on: ubuntu-latest

    steps:
      - name: Clone repositório
        uses: actions/checkout@v4

      - name: Configura Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Configura cache do Maven
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: maven-${{ runner.os }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            maven-${{ runner.os }}-

      - name: Run testes
        run: mvn clean test

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Build and exec tests with Maven
        run: mvn test -Dgroups=todos -Denv=prd
        continue-on-error: true

      - name: Get allure history
        uses: actions/checkout@v2
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Allure Report action
        uses: simple-elf/allure-report-action@master
        with:
          allure_results: target/allure-results
          allure_history: allure-history/allure-history
          keep_reports: 5

      - name: Deploy report to Github Pages
        if: github.ref == 'refs/heads/master'
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          folder: allure-history/allure-history
